version: "3.3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: chat
      POSTGRES_PASSWORD: password
  # proxy:
  #   build: ./proxy-server
  #   restart: always
  #   ports:
  #     - 4000:4000
  #   environment:
  #     - BACK_URL=http://back:3000
  #     - FRONT_URL=http://front:5000

